services:
  app:
    image: 'itsalexandermedvedev/task-manager:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=pass
      - SPRING_JPA.HIBERNATE.DDL-AUTO=update
      - SPRING.SECURITY.USER.PASSWORD=pass
    ports:
      - "8080:8080"

  db:
    image: 'postgres:16.2-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
    volumes:
      - database:/data/db
    ports:
      - "5433:5432"

volumes:
  database: